apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  clusterIP: None  # This enables headless service, good for StatefulSets
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql